language: R

sudo: false

cache:
  packages: true

jdk:
  - oraclejdk8

r_packages:
  - covr

env:
  - SPARK_VERSION="1.6.3"
  - SPARK_VERSION="2.1.0"
  - SPARK_VERSION="2.2.0"

after_success:
  - Rscript -e 'library(covr); codecov()'
